name: Deploy to Kali

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy app
        run: |
          set -e
          cd /home/kali/pradipshrees.github.io
          git pull origin main
          docker compose up -d --build